version: '3.1'
services:
  odc-adapter-ckan:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-adapter-ckan
    volumes:
      - odc-adapter-ckan_repo:/ids/repo
    environment:
      - REPOSITORY=/ids/repo
      - SERVICE_PORT=8080

  odc-adapter-postgres:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-adapter-postgres
    volumes:
      - odc-adapter-postgres_repo:/ids/repo
    environment:
      - REPOSITORY=/ids/repo
      - SERVICE_PORT=8080

  odc-config-manager:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-config-manager
    volumes:
      - odc-config-manager_repo:/ids/repo
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8091:8080
    environment:
      - REPOSITORY=/ids/repo/
      - INIT=true
      - SERVICE_PORT=8080

  odc-adapter-gateway:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-adapter-gateway
    links:
      - odc-config-manager
      - odc-adapter-ckan
      - odc-adapter-postgres
    environment:
      - CONFIG_MANAGER_URL=odc-config-manager
      - CONFIG_MANAGER_PORT=8080
      - SERVICE_PORT=8080

  db:
    image: postgres
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - odc-manager-database:/var/lib/postgresql/data
    environment:
      - DATABASE_USER=ids
      - DATABASE_USER_PW=ids

  odc-manager:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-manager
    depends_on:
      - db
    links:
      - odc-adapter-gateway
    ports:
      - 8090:8080
    environment:
      - HOST=db
      - PORT=5432
      - DATABASE=ids
      - USER=ids
      - PASSWORD=ids
      - FRONTEND_ADMIN=admin
      - FRONTEND_ADMIN_PW=admin
      - GATEWAY_HOST=odc-adapter-gateway
      - GATEWAY_PORT=8080
      - INIT=true
      - SERVICE_PORT=8080

  odc-frontend:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile-odc-frontend
    ports:
      - 8080:8080

volumes:
  odc-adapter-ckan_repo:
  odc-adapter-postgres_repo:
  odc-config-manager_repo:
  odc-manager-database:
  odc_adapter_ckan_tmp:
